### ISSUE TITLE
Make sliders work out of the box

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#103]
The sliders will change the settings in the settings files but RD doesn't apply them. If you restart rancher you get an error that requires running a console command to fix. This should be an intuitive experience.

**Comment by ericpromislow** [comment]
Possible workflow:
1. After changing the slider, a status bar message or notification tells the user the change will take effect after pressing "Reset K8s".
2. On "Reset K8s", if the cluster needs to be recreated, the system carries that out, with progress feedback to the user (since it takes a long time).

**Comment by satadruroy** [comment]
A slight tweak to the workflow like:

"You have changed settings that require a reset of the cluster. The cluster now will be reset" and then offer to reset the cluster for the user with an ok/cancel button? But with the reset the user would lose all their deployments so maybe we should also pop up some warning text when they click ok.

**Comment by mook-as** [comment]
Hmm, opinion time.  I currently have:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/3977982/108443137-1bb63780-720d-11eb-8fae-8a87660b4fa2.png">

That's not great, because the banner overlap some controls.  However, we currently don't have a status bar area, so if I stuck it at the bottom of the screen it could get hidden behind scrolling.
I guess that means I need to modify that page in particular to add a fixed area at the bottom to hold banners?

I'm intentionally not going for https://github.com/rancher-sandbox/rd/issues/103#issuecomment-777131056 because that sounds like a modal dialog box, and it wouldn't work well if the user wants to adjust both CPU and memory.
