### ISSUE TITLE
k3s fast reset and keep containerd content

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#104]
When one clicks on the "Reset Kubernetes" button k8s shuts down, the VM is deleted, a new one is created, and k8s is brought back up. This is left over from the way minikube does things by default.

Instead, when the "Reset Kubernetes" button is clicked k3s should be deleted and recreated. containerd should not be reset and images in containerd should stay cached in its location. Note, workloads running in k3s should be killed.

**Comment by mook-as** [comment]
This might interact badly with #103 — currently `reset kubernetes` works to rebuild the cluster; if we just make it wipe out k3s, we'll need something else for the current stronger level of reset.  We could still proceed to implement the task as-described, of course.

Also, how should stale images be deleted in the new world? Just let them age out automatically?

Rough sketch of the levels of reset we could do, where each one includes all previous ones:

- Nothing. (This would not be an UI option, of course.)
- Remove all non-default Kubernetes resources. (Probably not actually useful.)
- Remove k3s, reinstall.
- Remove k3s, all containerd images, etc.
- Remove the VM and rebuild.
- Remove all rd configuration including the VM (i.e. factory reset).

**Comment by jandubois** [comment]
> Also, how should stale images be deleted in the new world? Just let them age out automatically?

Kubelet already does this automatically I think: https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#image-collection

I don't see any advantage to interfering with that.

> Rough sketch of the levels of reset we could do, where each one includes all previous ones:
> 
> * Nothing. (This would not be an UI option, of course.)
> * Remove all non-default Kubernetes resources. (Probably not actually useful.)

I agree: not useful.

> * Remove k3s, reinstall.

Could be as easy as this:

```
$ m ssh sudo systemctl stop k3s
$ m ssh "sudo rm -rf /var/lib/k3s/server/db"
$ m ssh sudo systemctl start k3s
```

(I have since renamed the servicename from `k3s` → `kubelet` (for reasons); not sure if that change is in the version RD currently uses.

> * Remove k3s, all containerd images, etc.

I don't see a reason to have this; just delete the whole VM; it just takes a couple seconds longer.

> * Remove the VM and rebuild.

Sure.

> * Remove all rd configuration including the VM (i.e. factory reset).

This is questionable; you should never need to do this, and your can always delete and re-install. But I guess it would require a way to detect that you re-installed, and then ask if you want to re-use the old config, or start over.

I was wondering if this list was missing "Downgrade k3s but keep all images", but I guess this is just a special variant of "Remove k3s and reinstall" with a version change.

**Comment by mook-as** [comment]
> > * Remove all rd configuration including the VM (i.e. factory reset).
> 
> This is questionable; you should never need to do this, and your can always delete and re-install. But I guess it would require a way to detect that you re-installed, and then ask if you want to re-use the old config, or start over.

Right, "delete and re-install" wouldn't change user preferences (since all of that lives outside the app bundle).  The app bundle itself should be completely immutable, so deleting it and putting it back (perhaps somewhere else) shouldn't really matter.

> I was wondering if this list was missing "Downgrade k3s but keep all images", but I guess this is just a special variant of "Remove k3s and reinstall" with a version change.
Yep.
