### ISSUE TITLE
Unknown bootstrapper - another new machine issue

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rd#126]
When starting up on a new machine:

1. Without running `npm run setupmac`:

```
X Exiting due to MK_BOOTSTRAPPER: unknown bootstrapper: k3s
```

2. After having run `npm run setupmac`:

```
X Exiting due to MK_BOOTSTRAPPER: unknown bootstrapper: <empty string>

The dialog box contains a useless long block of code, consisting mostly of the status line 

```
> minikube-v1.17.0.iso: <NUM> MiB / 212.69 MiB  <PROGRESS>% <NUM> MiB p/s ETA <ETA TIME>
```

repeated over and over without line breaks.

```

**Comment by jandubois** [comment]
> When starting up on a new machine:
> 
> 1. Without running `npm run setupmac`:
> 
> ```
> X Exiting due to MK_BOOTSTRAPPER: unknown bootstrapper: k3s
> ```

Since you have never downloaded the RD version of minikube, this seems to indicate that RD is running a different minikube binary it finds somewhere on the `PATH`. Should we consider this a bug? Should we rename the bundled `minikube` to some different/obscure name to prevent this from happening by accident?

> 1. After having run `npm run setupmac`:
> 
> ```
> X Exiting due to MK_BOOTSTRAPPER: unknown bootstrapper: <empty string>
> ```

This is a bug in minikube that needs to be fixed if we decide to stick with minikube. The k3s version stores the bootstrapper ("kubeadm" or "k3s") in the local cluster config. When reading a config, it should default to "kubeadm" when not set, but there are many places that read a config, and some don't seem to set the default.

But we really only get this error because RD was running a non-bundled version of minikube that wrote the incompatible cluster config to the private RD config area. So with the first issue fixed, the second should never happen anyways.

**Comment by ericpromislow** [comment]
No, I don't have any other minikube in the path -- I linked resources/darwin/minikube to /usr/local/bin/ so it either picked that one up or ran its internal one.

3 days and I still haven't installed any k8s thing yet (Docker.app is installed but I haven't launched it).

Here's the initial default config from `~/.kube`:
```
{
  "apiVersion": "v1",
  "clusters": [],
  "contexts": [],
  "current-context": null,
  "kind": "Config",
  "preferences": {},
  "users": []
}
```

desktop wasn't happy with a missing config, and minikube wasn't happy if it didn't see `kind: Config`. Any ideas what exactly should be in this file on startup?

**Comment by ericpromislow** [comment]
After reading the code I think `setupmac` should ensure there's a k8s installation with context name 'rancher-desktop', rather than do that during app startup and deal with letting the user know about that through a GUI interface rather than a CLI

**Comment by jandubois** [comment]
> No, I don't have any other minikube in the path

I don't understand how that would be possible:

> X Exiting due to MK_BOOTSTRAPPER: unknown bootstrapper: k3s

That error message comes from a different minikube than the one included in RD. Or you have been running a very old binary/branch before minikube was bumped to the version with k3s support.

**Comment by ericpromislow** [comment]
Workaround: set `./.minikube/profiles/rancher-desktop/config.json::Bootstrapper = 'k3s'`
