### ISSUE TITLE
Repeatedly installing homestead

### ISSUE THREAD

**Issue by mook-as** [rancher-sandbox/rd#134]
It appears that we're ending up going through [`ensureHelmChart()`](https://github.com/rancher-sandbox/rd/blob/97d2962358d6e02c586944de655e5961a64c0f38/src/k8s-engine/homestead.js#L117) multiple times concurrently, leading to issues because `helm list` would return empty (because it hasn't been installed yet, it's in progress), and then attempting to run `helm install` again, which errors out (because an install is in progress).  This leads to a dialog box on startup about not being able to install homestead, and then the cluster goes into an error state.

**Comment by ericpromislow** [comment]
Part of this is due to the transition from Homestead to Rancher and having a rogue value in the settings. I'm detecting the normal transition of going from prefs version 1 to 2, dropping "HOMESTEAD" for "RANCHER", but going the other way requires a different approach.  Added it while working on this issue.

**Comment by mattfarina** [comment]
Closing as we are removing homestead/rancher. It will no longer be part of the mvp.
