### ISSUE TITLE
Hyperkit for Mac

### ISSUE THREAD

**Issue by gaktive** [rancher-sandbox/rd#145]
Replacing the work done in #6

**Comment by jandubois** [comment]
Using [v2.0.0-alpha.1](https://github.com/rancher-sandbox/docker-machine-driver-hyperkit/releases/tag/v2.0.0-alpha.1):

## Download and prepare docker-machine-driver-hyperkit

```
curl -sLO https://github.com/rancher-sandbox/docker-machine-driver-hyperkit/releases/download/v2.0.0-alpha.1/docker-machine-driver-hyperkit
chmod +x ./docker-machine-driver-hyperkit
sudo chown root:wheel ./docker-machine-driver-hyperkit
sudo chmod +s ./docker-machine-driver-hyperkit

curl -sLO https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
```

Downloading the ISO is not strictly necessary, as `docker-machine-driver-hyperkit` will fetch it automatically. Not sure if we want to bundle it or not..

## Starting k3s

The [run-k3s](https://github.com/jandubois/tinyk3s/blob/main/run-k3s) script from tinyk3s doesn't work right now for this image; here is a simplified local version (remember to make it executable):

```
$ cat ./run-k3s
#!/bin/sh

set -o errexit -o nounset -o pipefail -o xtrace

CACHE=/k3s-cache
VERSION=v1.20.2+k3s1

mkdir -p /etc/rancher/k3s
mkdir -p /var/lib/rancher/k3s/agent/images
ln -s $CACHE/$VERSION/k3s-airgap-images-amd64.tar /var/lib/rancher/k3s/agent/images
ln -s $CACHE/$VERSION/k3s /usr/local/bin

/usr/local/bin/k3s server
```

Starting the VM and k3s:

```
./docker-machine-driver-hyperkit -s $HOME/.rd start --iso-url ./boot2docker.iso --cpus 2 --memory 8192 --disk-size 60000 --volume ~/.tinyk3s:/k3s-cache --volume $PWD:/host --volume /Volumes/ThunderBlade/suse/tinyk3s:/tinyk3s
./docker-machine-driver-hyperkit -s $HOME/.rd ssh sudo /host/run-k3s
```

The `/host` mount is just to map in the local `run-k3s` script, and `/tinyk3s` to use it's `kubeconfig` script (in a different shell, because the command above run `k3s server` in the foreground):

```
export KUBECONFIG=~/kubeconfig.yaml
./docker-machine-driver-hyperkit -s ~/.rd ssh sudo /tinyk3s/kubeconfig > $KUBECONFIG
k get no
k get po -A
```

## Deleting the VM

```
./docker-machine-driver-hyperkit -s $HOME/.rd delete
```

## Known issues

I have quite a long list, possibly relevant to MVP are:

* VM does not disable password based login and ships with the default boot2docker credentials
* `~/.rd/cache` directory is owned by `root`
* `/etc/exports` file doesn't get cleaned up properly on exit
* Volume mounts to symlinked directories don't work
* There is no command to stop/restart the VM yet

**Comment by jandubois** [comment]
Removed @mook-as because his work is tracked by #159.

I've attached links to updated binaries to that ticket.

**Comment by mook-as** [comment]
Given that #192 is merged, do we mark this one as done now?

**Comment by jandubois** [comment]
> Given that #192 is merged, do we mark this one as done now?

Let's keep it open until I have produced `alpha.3`. Then we can create new issues for anything that comes up after (and maybe even in the `docker-machine-driver-hyperkit` repo if it isn't directly related to the RD code.

**Comment by mattfarina** [comment]
Since we are now using hyperkit on mac I'm going to close this. We can open up other issues for anything new we encounter.
