### ISSUE TITLE
RD on Windows

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#15]
We need to have RD running on Windows and that includes Windows Home where there is no hypervisor. Instead of a normal hypervisor we should use Windows Subsystem for Linux (likely v2). WSL is available on Windows 10 Home.

With WSL we could either install and manage k3s in an existing Linux or start up a custom Linux setup and expose K3s to windows and the other Linux instances from there. This is open for discussion.

This isn't going to use Minikube as minikube on Windows doesn't work with WSL to manage the things.

**Comment by mook-as** [comment]
FWIW, Docker on Windows (when on Windows 10 Home) only runs via WSL2; there it appears to act like nested containers — it runs a Microsoft-shipped Linux kernel, and each distribution gets their own chroot / pid namespace (but appears to have a shared network namespace).  They also have a HyperV backend, but HyperV is only available on Pro+ Windows licenses.

**Comment by mattfarina** [comment]
@mook-as k3s runs in linux under WSLv2. The questions will be... which Linux do we use and why? Is it a separate one from the users or right in a users linux setup? How do we install and how do we bridge k8s to Windows?

We can't use Hyper-V because running in Windows Home is a priority.

**Comment by mattfarina** [comment]
The deliverable for this issue is the WSL/k3s setup that can later be connected to the app/UI via #147

**Comment by jandubois** [comment]
I've written up instructions as part of the release notes for [tinyk3s-v0.1](https://github.com/jandubois/tinyk3s/releases/tag/v0.1).

I intend to tweak this setup further in the future, but it should be good enough to get started with RD for now.

Maybe try all the steps manually once, to verify that they are working on other machines beside my VM?

And let me know if I missed to explain some scenario!

Since we don't have an init system like systemd under WSL, we'll need to do some monitoring/restarting at the RD level, but I assume that is outside the scope of this issue.

**Comment by mook-as** [comment]
I've get as foar as `kubectl.exe get pods -A` on my (non-VM) Windows machine.  The only thing relevant was that I had to install WSL first (this was a _fresh_ install).

Also, I didn't bother with the shell script - I just downloaded files manually and put them in the right places.

Suggestions, for later:
- Should point to instructions to set up WSL (or better, have RD do it for the user).
- `run-k3s` shouldn't daemonize — it should just run in the foreground, and we can get RD to do the backgrounding.  That should (hopefully) also solve issues you were having with process management.
- I assume we'd override `CACHE_DIR` from the RD end, so the cache directory thing isn't an issue.

**Comment by mook-as** [comment]
Notes on getting a RD dev environment on Windows:

Dependencies:
- [Visual Studio 2019 Community](https://visualstudio.microsoft.com/vs/) (the license should be okay, because RD is Apache 2.0, which is OSI-approved), with `MSVC v141 - VS 2017 C++ x64/x86 build tools (v14.16)`
- Python 2 (VS seems to be able to install one)
- GTK 2 (for [canvas](https://www.npmjs.com/package/canvas)) — I used the [bundle](http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/) as instructed on the wiki.
- [libjpeg-turbo](https://sourceforge.net/projects/libjpeg-turbo/files/2.0.6/), also for canvas.
-   Build RD with `set GYP_DEFINES="GTK_Root=C:/Path/To/GTK2" jpeg_root="C:/Path/to/libjpeg"`.  Under `cmd.exe`, `set` takes the rest of the line, no need to worry about quoting.
- Manually run `npm install nan@2.14.0` because https://github.com/nodejs/nan/issues/892

With that, `npm install` will _hopefully_ work.  Not even trying to build yet.

I may have missed stuff; feel free to edit this comment to update the instructions.

**Comment by mook-as** [comment]
Closing, because things landed and WSL-based RD should work now (with lots of polish needed).
