### ISSUE TITLE
On Windows add CLIs to path

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#174]
The immediate reason is to add applications (kim, helm, kubectl) to the path on Windows.

**Comment by mook-as** [comment]
Looking into the implementation, electron-builder has inadequate customization capabilities in msi (wix) mode; we'll have to stick with the NSIS installer.  In particular, we don't seem to be able to use the [`QtExec`](https://wixtoolset.org/documentation/manual/v3/customactions/qtexec.html) extension, because there's no way to provide `-ext WixUtilExtension` on the `light` command line (even if we [hack in the template](https://stackoverflow.com/questions/55460379/x/55538792)).
