### ISSUE TITLE
Install/setup WSL if not present when RD is run/installed

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#185]
We should look to see how to do this in the MSI

**Comment by ericpromislow** [comment]
Here are my steps for manually installing wsl:
```

Open Powershell (or regular shell) as admin

[ ] dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

[ ] dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

[ ] Restart the machine

[ ] Start edge, move to https://docs.microsoft.com/en-us/windows/wsl/install-win10

[ ] Download https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

[ ] Open and run wsl_update_x64.msi

[ ] wsl --set-default-version 2
```

Consider this a starting point rather than the final word. Step 3 might not be necessary, unless the MSI requires it.

**Comment by mook-as** [comment]
Notes on how I want the installer to work, before I figure out how to make that actually happen:
- The installer should always run elevated, because it needs to be able to add Windows features (`Microsoft-Windows-Subsystem-Linux`, `VirtualMachinePlatform`).
- The install should be per-user.
- We should prompt for reboot, because that may be required for Windows feature changes. This means the installer should not run silently (at least when invoked manually).
