### ISSUE TITLE
Add Rancher Desktop icon for Windows

### ISSUE THREAD

**Issue by sirredbeard** [rancher-sandbox/rd#223]
The Rancher Desktop icon does not appear in the title bar or on the task bar in Windows, it still defaults to the Electon app default.

The Rancher Desktop icon should be updated in the title bar and on the Windows task bar. 

![image](https://user-images.githubusercontent.com/33820650/116727435-92607580-a9b2-11eb-8602-51a73af68ee5.png)

![image](https://user-images.githubusercontent.com/33820650/116727467-9ab8b080-a9b2-11eb-8147-abc6de4894c4.png)

**Comment by mook-as** [comment]
This may have been fixed since; with a build off `main`, I have:
![image](https://user-images.githubusercontent.com/3977982/118055120-5d520c80-b33c-11eb-8c31-d308607bfd24.png)
![image](https://user-images.githubusercontent.com/3977982/118055132-65aa4780-b33c-11eb-989b-35e6eaa02832.png)

Note that this is from the installer; it's expected that the icons would be wrong when running under `npm run dev`.
