### ISSUE TITLE
RD needs to fail gracefully on WSL-less Windows

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rd#254]
On a Windows 10 VM, I uninstall `wsl` and ran `npm run dev`. I get a message box saying `Error Starting Kubernetes` with a smaller line `spanw wsl.exe ENOENT`.

The second line should be translated to something friendlier like `It looks like WSL (the Windows Subsystem for Linux) is not installed.  See <link to instructions on installing it>.` and then the app should shut down.

## Even worse

I can't quit the (debug) app by right-clicking PC Cow and selecting `Quit Rancher Desktop`, probably related to this output:

```
2: Child exited with code undefined
Kubernetes was unable to start with exit code: undefined
```

**Comment by mook-as** [comment]
The **Even worse** section is related to #258, combined with Electron not letting you interact with the tray while the dialog box is up (presumably because they have blocked the main message queue while the dialog box is up, so the JS can't handle the tray icon menu or something).  Going to ignore that for this PR.

**Comment by mook-as** [comment]
I have a [branch](https://github.com/mook-as/rd/tree/win-handle-no-wsl) with this work, but it makes no sense to merge it before #261 - it changes approximately the same code.
