### ISSUE TITLE
Stratos UI

### ISSUE THREAD

**Issue by mattfarina** [rancher-sandbox/rd#55]
[Stratos](https://github.com/cloudfoundry/stratos), the Cloud Foundry UI that can also do Kubernetes and Helm, is a UI we've invested heavily in and that can be [built as an electron app](https://github.com/cloudfoundry/stratos/tree/master/electron). We should look at how to incorporate it into RD. This includes:

- Should we incorporate it with reasons?
- How do we pull it in and make it part of RD?
- Exposing through the menu next to Dashboard
- What elements should be available? Should CF be displayed by default? Is this configurable?

**Comment by mook-as** [comment]
I have a [work-in-progress branch](https://github.com/mook-as/rd/tree/stratos), but now I'm trying to figure out if there's better packaging.

Constraints:
- Stratos requires a backend executable (jetstream), which means it must not be in the electron asar package.
- That requires access to the frontend files on disk, so that must not be packaged either.

That means:
- I don't see how packaging stratos as a npm package could work, since access to the files (as raw files and not wrapped in JS) would be… interesting, especially with electron packaging. But probably still doable.
- Which means it's probably best done completely separately from nuxt/webpack/etc.

@mattfarina / @nwmac please sanity check my thinking?

**Comment by mattfarina** [comment]
Closing as stratos and the UI to look at k8s resources is no longer in scope for mvp or just following that. We will revisit the UI in the future but _how_ and _when_ we do that are not yet determined. I would expect it to be _after_ Rancher 2.6.
